DEMO_WORKS = [
    {"slug":"moonlit-archive","title":"The Moonlit Archive","author":"Aiko Mori","category":"Manga","volume":"Vol. 1","description":"A quiet fantasy about a night librarian who discovers that unfinished stories keep changing after midnight.","copies":3,"available":2,"length":"192 pages","cover":"moonlit-archive.svg","featured":True,"popular":True,"recent":False},
    {"slug":"city-after-rain","title":"City After Rain","author":"Noah Bell","category":"Graphic Novels","volume":"","description":"Two strangers cross paths across a rain-soaked city in a reflective graphic novel about memory and second chances.","copies":2,"available":1,"length":"224 pages","cover":"city-after-rain.svg","featured":True,"popular":False,"recent":True},
    {"slug":"orbit-house","title":"Orbit House","author":"Mina Vale","category":"Comics","volume":"Issue 07","description":"A found-family science fiction series set aboard a station that should have been decommissioned years ago.","copies":4,"available":0,"length":"48 pages","cover":"orbit-house.svg","featured":False,"popular":True,"recent":False},
    {"slug":"paper-garden","title":"The Paper Garden","author":"Eleanor Wren","category":"Literature","volume":"","description":"A lyrical collection of linked stories about a family bookshop, inheritance, and the ways objects carry memory.","copies":5,"available":4,"length":"286 pages","cover":"paper-garden.svg","featured":True,"popular":True,"recent":False},
    {"slug":"salt-library","title":"The Salt Library","author":"Inez Rowan","category":"Novels","volume":"","description":"On an island where every household keeps a private archive, a missing ledger threatens to expose a town's oldest promise.","copies":3,"available":1,"length":"348 pages","cover":"salt-library.svg","featured":False,"popular":True,"recent":True},
    {"slug":"signal-quarterly","title":"Signal Quarterly","author":"Editorial Collective","category":"Magazines","volume":"No. 18","description":"A quarterly magazine covering illustration, independent publishing, print culture, and visual storytelling.","copies":6,"available":5,"length":"112 pages","cover":"signal-quarterly.svg","featured":False,"popular":False,"recent":True},
    {"slug":"lantern-days","title":"Lantern Days","author":"Haru Sato","category":"Manga","volume":"Vol. 4","description":"A slice-of-life series following four art students through a final summer in their coastal hometown.","copies":2,"available":2,"length":"176 pages","cover":"lantern-days.svg","featured":False,"popular":True,"recent":True},
    {"slug":"north-window","title":"The North Window","author":"Sofia Reyes","category":"Literature","volume":"","description":"Essays on place, reading, migration, and the small rituals that make unfamiliar rooms feel like home.","copies":2,"available":0,"length":"240 pages","cover":"north-window.svg","featured":False,"popular":False,"recent":True},
    {"slug":"neon-fables","title":"Neon Fables","author":"Cal Mercer","category":"Comics","volume":"Book Two","description":"Short urban myths retold through bold sequential art and strange, luminous city folklore.","copies":3,"available":3,"length":"136 pages","cover":"neon-fables.svg","featured":False,"popular":True,"recent":False},
    {"slug":"summer-atlas","title":"A Summer Atlas","author":"Mara Dela Cruz","category":"Novels","volume":"","description":"A warm coming-of-age novel about mapping a changing neighborhood before its old landmarks disappear.","copies":4,"available":2,"length":"312 pages","cover":"summer-atlas.svg","featured":True,"popular":False,"recent":False},
    {"slug":"frame-by-frame","title":"Frame by Frame","author":"Studio Nineteen","category":"Magazines","volume":"No. 06","description":"Interviews and visual essays on comics craft, lettering, page rhythm, and independent publishing.","copies":2,"available":1,"length":"96 pages","cover":"frame-by-frame.svg","featured":False,"popular":False,"recent":True},
    {"slug":"small-hours","title":"Small Hours","author":"June Harlow","category":"Graphic Novels","volume":"","description":"An intimate graphic novel about overnight work, insomnia, and the people who keep a city moving before dawn.","copies":3,"available":2,"length":"208 pages","cover":"small-hours.svg","featured":False,"popular":True,"recent":True},
]

CATEGORIES = ["Manga", "Comics", "Literature", "Novels", "Magazines", "Graphic Novels"]

